# version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

  vueapp:
    build:
      context: ./app/vueapp
      dockerfile: Dockerfile
    container_name: vueapp
    command: npm run serve
    volumes:
      - ./app/vueapp:/app
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
